var user = {
"login": "saintvictoria",
"id": 8070653,
"avatar_url": "https://avatars.githubusercontent.com/u/8070653?v=2",
"gravatar_id": "",
"url": "https://api.github.com/users/saintvictoria",
"html_url": "https://github.com/saintvictoria",
"followers_url": "https://api.github.com/users/saintvictoria/followers",
"following_url": "https://api.github.com/users/saintvictoria/following{/other_user}",
"gists_url": "https://api.github.com/users/saintvictoria/gists{/gist_id}",
"starred_url": "https://api.github.com/users/saintvictoria/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/saintvictoria/subscriptions",
"organizations_url": "https://api.github.com/users/saintvictoria/orgs",
"repos_url": "https://api.github.com/users/saintvictoria/repos",
"events_url": "https://api.github.com/users/saintvictoria/events{/privacy}",
"received_events_url": "https://api.github.com/users/saintvictoria/received_events",
"type": "User",
"site_admin": false,
"name": "Victoria Nicholson",
"company": "",
"blog": "",
"location": "",
"email": "saintvictoria@gmail.com",
"hireable": false,
"bio": null,
"public_repos": 9,
"public_gists": 0,
"followers": 1,
"following": 0,
"created_at": "2014-07-04T19:19:02Z",
"updated_at": "2014-10-08T12:26:51Z"
}
